### ISSUE TITLE
Error on M1 mac build

### ISSUE THREAD

**Issue by nonfungibletunji** [apple/swift-container-plugin#35]
### Description

swift package --swift-sdk x86_64-swift-linux-musl \ 
        build-container-image --repository registry.orb.local/myservice

Emitting module UnixSignals
/Users/stunjiturner/Downloads/CascadeProjects/hummingbird-sightmedialab/.build/checkouts/swift-service-lifecycle/Sources/UnixSignals/UnixSignal.swift:22:8: error: compiled module was created by a different version of the compiler ''; rebuild 'Dispatch' and try again: /Users/stunjiturner/Library/org.swift.swiftpm/swift-sdks/swift-6.0.2-RELEASE_static-linux-0.0.1.artifactbundle/swift-6.0.2-RELEASE_static-linux-0.0.1/swift-linux-musl/musl-1.2.5.sdk/aarch64/usr/lib/swift_static/linux-static/aarch64/Dispatch.swiftmodule
 20 | import Musl
 21 | #endif
 22 | import Dispatch
    |        `- error: compiled module was created by a different version of the compiler ''; rebuild 'Dispatch' and try again: /Users/stunjiturner/Library/org.swift.swiftpm/swift-sdks/swift-6.0.2-RELEASE_static-linux-0.0.1.artifactbundle/swift-6.0.2-RELEASE_static-linux-0.0.1/swift-linux-musl/musl-1.2.5.sdk/aarch64/usr/lib/swift_static/linux-static/aarch64/Dispatch.swiftmodule
 23 | 
 24 | /// A struct representing a Unix signal.

### Reproduction

_[Please provide inputs to help us reproduce the problem.   Try to reduce the test case to the smallest amount of code possible which still reproduces the problem.]_

### Package versions

latest

### Expected behavior

_[Describe what you expect to happen.]_

### Environment

swift-driver version: 1.115 Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0

### Additional information

i am using SDK
swift-6.0.2-RELEASE_static-linux-0.0.1

**Comment by euanh** [comment]
This error can occur if you try to use the Static Linux SDK with the Swift toolchain which comes with Xcode.   The Static Linux SDK can only be used with an open source Swift toolchain from swift.org:

   https://www.swift.org/documentation/articles/static-linux-getting-started.html#installing-the-sdk

Please check that you have installed the 6.0.2 swift.org toolchain:

  https://www.swift.org/install/macos/package_installer/

Once the swift.org toolchain is installed, you can use it by setting the `TOOLCHAINS` environment variable:
```
export TOOLCHAINS=$(plutil -extract CFBundleIdentifier raw /Library/Developer/Toolchains/swift-6.0.2-RELEASE.xctoolchain/Info.plist)
swift package --swift-sdk x86_64-swift-linux-musl build-container-image --repository registry.orb.local/myservice
```

**Comment by euanh** [comment]
@nonfungibletunji Were you able to build your container image?
