### ISSUE TITLE
HTTPTypesFoundation/HTTPRequest+URL.swift:126: Precondition failed: Schemeless URL is not supported

### ISSUE THREAD

**Issue by jcalderita** [apple/swift-container-plugin#43]
Problems uploading image to ghrc

swift package --swift-sdk x86_64-swift-linux-musl --allow-network-connections all \
    build-container-image --repository ghcr.io/username/appname:latest --verbose
Building for debugging...
[1/1] Write swift-version-46686AC6179D828D.txt
Build of product 'containertool' complete! (2.35s)
Building for debugging...
[0/2] Write swift-version-46686AC6179D828D.txt
Build of product 'appname' complete! (2.67s)
[ContainerImageBuilder] Connected to source registry: index.docker.io
[ContainerImageBuilder] Connected to destination registry: ghcr.io
Using base image: index.docker.io/library/swift:slim
[ContainerImageBuilder] Found base image manifest: sha256:6c9cdab60bafd1be47262bda80123012fce264d2e7ee5683bb2b9be872332a0a
[ContainerImageBuilder] Found base image configuration: sha256:aa83638093052d81505fef76461c4245e7ff5bfae308894f83ac6b6ad1285ac5
[ContainerImageBuilder] Built application layer
[ContainerImageBuilder] Uploading application layer
[ContainerImageBuilder] HTTPTypesFoundation/HTTPRequest+URL.swift:126: Precondition failed: Schemeless URL is not supported

**Comment by euanh** [comment]
Hi @jcalderita.   Thank you for reporting this problem.  I can reproduce it.

**Comment by euanh** [comment]
@jcalderita Please try 0.3.1 and let me know if you still run into this problem.

**Comment by jcalderita** [comment]
Works perfectly, thank you very much. 🎉
